- relay.js
`await untilOpen` would cause to hang if there was an error.  This would cause the UI to hang even if other relays were connected, since the await is in a loop.
The key to this PR is adding the `rejectOpen`(also renamed `isOpen` to `resolveOpen` for clarity), this will keep the hang up.  This will more than likely have upstream effects but less severe than the hang, additional handling most likely needed in the client app, but it appears to work for now.
Also, I wrapped the `await` in the `trySend` which has additional checks for the web socket status.
This will also try to reconnect on an interval if previous connection failed.
> remove hanging if no connection

- relay.js
This provides a way for a client to check if a relay is online by checking against `WebSocket.OPEN`.  Or it could be just an `online` getter instead that checks internally, whatever you like, not sure if there is an advantage to checking the other states or not.
> Provide client access to relay status

- pool.js
- relay.js
I think most of these changes should be obvious, relay.js line 89, id does not exist so removed from log
The bind on the channel was only bound once, on return so it kept the same value for every subscription.  I moved it to `sub` and also added the reduce to convert to hex
And `trySend` already stringifies, so it was removed from `realy.publish`
> Correct subscriptions for new protocol

- keys.js
'Buffer' wasn't imported initially and was causing issues when I tried to use generatePrivateKey in a client I am building. not sure why Branle has no error, maybe I am doing something wrong?
> import 'Buffer'

- package.json
- pool.js
- relay.js
Using the `beforeSend` hook on Branle, adding `since` to each filter to the main subscription.
```js
beforeSend: ({filter, relay}) => {
console.log(`beforeSend: filters for relay: ${relay}`, filter)
const newFilter = filter.map(f => ({
...f,
since: Math.floor(Date.now() / 1000) - 24 * 60 * 60
}))
return {filter: newFilter}
},
```
> feat: add beforeSend hook to sub()

- nip04.js
I'm from Asia and I found that CJK characters are garbled after decryption.
Because during decryption, parameters of `decipher.update` does not contain `outputEncoding`.
Test code:
```Javscript
import { decrypt, encrypt } from './nip04.js'
const main = function() {
let priv = '3277614521b0dba8ec930e64ff4ea5bb2709dfd67d35586b8b380d0beeb420c1'
let pub = '8643c759c757bbaf06eae40ac4454627ec44731a7f48a4ba04244b68fd028999'
let txt = '苟利国家生死以，岂因祸福避趋之'
let cipText = encrypt(priv, pub, txt)
let r = decrypt(priv, pub, cipText)
console.log(r)
}
main()
```
Result:
After repair:
> fix: CJK characters are garbled after decryption

- README.md
- index.js
- pool.js
- relay.js
hey fiatjaf and all,
here is my initial refactor of the call back api as proposed by fiatjaf. it replaces all the existing call back arguments with listeners that can be added to the pool, subscription, or relay (if using relay module without the pool module). only 'event' and 'eose' can listen at the sub level, but these can also listen at the pool or relay (again, only if using relay module without the pool module) level as well. current list of listener types:
- event
- eose
- connection
- disconnection
- error
- notice
format of the calls:
pool.on('connection', cb)
pool.on('event', cb)
sub.on('eose', cb)
relay.on('notice', cb)
this hasn't been thoroughly tested yet (though seems to work from cursory testing) but wanted to get eyes on this sooner rather then later in case I need to be …
> refactor of cb api

- relay.ts
Avoid error
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'readyState')
at get status [as status] (nostr.esm.js?9e27:346:1)
at eval (Nostr.ts?6cf9:77:1)
```
> relay.status() returns 0 when ws not created

- nip06.ts
There's no reason to expose clients to hex representation of mnemoic, as it's just one more format to think about.
> Don't expose external API to hex representation of mnemoic

- filter.ts
As per NIP-01 `limit` should be in the filter parameters.
> Add limit to filter

- relay.ts
Connect and close should return promises, the promise in close should be created before closing the socket, otherwise `resolveClose` is `undefined` in `ws.onclose`.
> Fix connect/close return types and race condition

- relay.ts
I apologize, my fix was misleading. The problem is that `ws.onclose` is also called when the socket is closed by the system (i.e. not us), in that case `resolveClose` isn't set (it's only set if we call the relay object's method `close`) so to prevent this error it should be checked. There's no race condition actually.
> Fix resolveClose

- relay.ts
If you try to use the `.on("error", ...` flow defined in the README, you currently get this error in editors:
In order to make sure that the type definitions are consistent throughout the file, I think it makes sense to extract this into its own type.
> Add missing "error" event to `on` and `off` type definitions

- relay.ts
In the README and the code, it looks like the second argument for the relay's `sub` method is optional:
```typescript
let sub = relay.sub([
{
ids: ['d7dd5eb3ab747e16f8d0212d53032ea2a7cadef53837e5a6c66d42849fcb9027']
}
])
```
In the type definitions it's required however, which leads to an error in editors:
Let's mark it as optional in the type definitions too! 👍
> Make `opts` arg optional for `sub` method

- event.ts
the use of id has been removed and the hash is computed instead
> fixed security issue around event verification

- build.js
- package.json
esm imports don't work currently because node decides whether a package is cjs or esm based on the `type` property in the nearest `package.json`. default value of `type` is `commonjs` which causes import/require import whatever is set for `main` which happens to be the cjs bundle. 
This PR fixes #124  by:
* auto-generating a minimal `package.json in `lib` dir nearest the esm bundle
* Noticed this package uses `cjs` bundle in all tests so adding `type: "module"` to root package.json would cause things to break.
* including the `exports` property in the root package.json to allow node environments to use cjs or esm bundles
> Make `esm` bundle usable in node 

- event.ts
Stumbled across this oversight when wondering why `nostr-tools` was validating my event but relays were rejecting it. Thanks for building this & nostr!
> ensure kind has type 'number' in validateEvent

- README.md
pool.publish does not return an array, but instead an object with two methods: 'on' and 'off'. Updated README.md to show how to handle "ok" events that follow pool.publish.
> Fixed readme for publishing with pool

- .github/workflows/test.yml
fixes ci warning
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> update actions/checkout to v3

- relay.ts
test `pool.test.js` was failing with error `TypeError: Cannot read properties of undefined (reading 'sendCloseFrame')`.
seems that (at least one) of the relays in the `relays` array is forcefully closing the connection, which was causing the error mentioned above, when trying to close the pool in `afterAll`.
`jest` was not exiting due to some websockets left unclosed. I think this is the reason that GitHub Actions workflow `test` has been failing recently (by exceeding the maximum execution time).
> close relay's websocket only if it's in state OPEN

- pool.ts
I noticed that SimplePool runs into issues if the conenction is cut off at any time. This is because ensureRelays checks if the connection already exists, but does not ensure that the connection is acutally open. With this small addition ensureRelay will check if a requested connection already exists inside SimplePool and will attempt to re-open is status does not equal 1
> Add .connect() to ensureRelay if connection exists, but status != 1

- event.test.js
**getBlankEvent** should return a blank event object.
**finishEvent** should create a signed event from a template.
**serializeEvent** should serialize a valid event object.
**serializeEvent**  should throw an error for an invalid event object.
**getEventHash** should return the correct event hash.
**validateEvent** should return true for a valid event object.
**validateEvent** should return false for a non object event.
**validateEvent** should return false for an event object with missing properties.
**validateEvent** should return false for an empty object.
**validateEvent** should return false for an object with invalid properties.
**validateEvent** should return false for an object with an invalid public key.
**validateEvent** should return false for an object with invalid tags. …
> add 17 test cases for event.js

- event.test.js
- filter.test.js
added 13 test cases for filter.ts
matchFilter
√ should return true when all filter conditions are met
√ should return false when the event id is not in the filter
√ should return false when the event kind is not in the filter
√ should return false when the event author is not in the filter
√ should return false when a tag is not present in the event
√ should return false when a tag value is not present in the event
√ should return true when filter has tags that is present in the event
√ should return false when the event is before the filter since value
√ should return false when the event is after the filter until value
matchFilters
√ should return true when at least one filter matches the event
√ should return true when event matches one or more filters and some have limit set
√ should …
> edit filter.test.js and add more test cases

- pool.ts
- relay.ts
Fixes a race condition in `relay.connect` and `pool.ensureRelay`.
On boot if the client issued several early `REQ` I noticed:
* multiple websocket connections would be opened, and only one used.
* a few `REQ` would be delayed by a second (from `trySend` when ws connection is not ready)
By adding a single `connectionPromise`, multiple concurrent calls to `connect()` will all block on the same promise and won't open up multiple websocket connections.
So calling `pool.ensureRelay` at top of program will avoid hitting the 1s timeout.  Possibly the timeout could be removed but not 100% sure on that.
> Reuse a connectionPromise for relay connect

- references.ts
https://github.com/nostr-protocol/nips/blob/e219ec64701d89e6b2c3f3ca8fd426d0aefdcb9c/33.md?plain=1#L47
> The equivalent in `tags` to the `naddr` code is the tag `"a"`, comprised of `["a", "<kind>:<pubkey>:<d-identifier>", "<relay url>"]`.
> fix: must be tag not ref.

- filter.test.js
- filter.ts
so clients can filter events by prefix ids as described in nip-01, i.e. to subscribe to mined events starting with zeroes or to add some privacy for clients that may not want to disclose the exact filter.
this is only a POC and does not support non-aligned (odd-length) hex prefixes.
see also https://github.com/scsibug/nostr-rs-relay/issues/104
part of https://github.com/nbd-wtf/nostr-tools/issues/157
> nip01: add support for filter prefix in authors and ids

- package.json
in addition to the just tasks, this commit adds npm scripts back, for convenience.
example taks:
- npm test
- npm test filter.test.js
- npm run build
- npm run format
in yarn it should just work without 'run' i.e. 'yarn build'.
> scripts: add npm build, format and test scripts

- event.ts
Improves the return type of validateEvent so it can act as a guard. This allows passing `unknown` into it to get back an `UnsignedEvent`. If you pass a more fully-qualified type like `Event`, it'll return the more detailed type. This is a backwards-compatible change.
> validateEvent: use assertion function

- event.ts
Fixes the regression in type-checking caused by #168 
It does two things:
1. Prefers `event instanceof Object` instead of `typeof event === 'object'`. The second way allows `null` while the first way does not. That could result in a runtime error.
2. Adds an `isRecord` function to coerce the type of `event`, allowing us to read arbitrary properties off it fixing the type errors.
> Fix validateEvent type checking

- nip05.test.js
- nip05.ts
This PR allows the use of dots in the `<local-part>` in `queryProfile(fullname)`
As described in https://github.com/nostr-protocol/nips/blob/master/05.md the `<local-part>` should include a dot: `a-z0-9-_.`
> fix(nip05): allow dot in name

- nip19.ts
Makes the return type of `nip19.decode` a [discriminated union](https://knowledgehub.hashnode.dev/typescript-discriminated-unions-a-guide-to-understanding), allowing you to use a `switch` statement on `result.type` and then `result.data` will be automatically inferred.
Eg:
```ts
const result = decode('1234...')
switch (result.type) {
case 'nprofile':
result.data // ProfilePointer inferred
break
case 'npub':
result.data // string inferred
break
}
```
> nip19: improve return type

- LICENSE
- README.md
- package.json
Unlicense is a slightly more formal public domain dedication. Info here: https://unlicense.org/
Benefits include:
1. It's just a public domain dedication, as you already intend
2. A proper SPDX identifier in package.json so automated tools can detect the license
3. GitHub will prominently display the license
4. It includes additional clarifying language
5. It's shorter than CC0, which is more in the spirit of Nostr
Side-note that unless you're using a copyleft license like the GPL, you basically need a CLA to ensure the code will be forever free when you accept outside contributions. However this affects most of open source code, including most projects under MIT. So I'm going to mostly ignore that for now, but I added a statement to the README to sorta cover it:
> By submitting patches …
> Add Unlicense

- README.md
- event.test.js
- event.ts
- pool.test.js
- relay.test.js
The existing `signEvent` function is named incorrectly. It should be called `getSignature`, which matches its partner function `getEventHash`. This is because it returns a _string_ instead of a signed event. Even NIP-07's `window.nostr.signEvent` function is correct, returning the signed event, but the one in this repo isn't.
This is a breaking change, but I think it's needed. The name of this function interferes with actual `signEvent` implementations.
> Rename signEvent to getSignature

- event.ts
Allows using types like `Event<3>` and `SignedEvent<1>`, etc.
Using plain old `Event` will still work, and it preserves the current behavior. With no arguments it will match only the known `Kind`s, but you can also use `Event<number>` to match any kind.
As a result you can can do awesome stuff like this, where your functions guard against particular kinds of events: https://gitlab.com/soapbox-pub/mostr/-/blob/c67064aee5ade5e01597c6d23e22e53c628ef0e2/src/activitypub/transmute.ts#L184
I've been using this pattern in all my Nostr projects. It doesn't have the full discriminated-union behavior I wish it did in switch statements, but for what's currently possible in TypeScript, it's a huge improvement.
This is a backwards-compatible change.
> Make Event a generic type accepting Kind

- event.test.js
- event.ts
Allow `getBlankEvent` accept a kind number and return `type` base the param passed.
There are the `type` of `e` and the `type` of `e.kind` which vscode detected.
It also accept a `number` of `Kind`, in this way `type` of `e.kind` is a number `1`.
> feat: getBlankEvent accept a kind

- filter.ts
Gives Filter a similar treatment as #199 
This allows you to write code like this:
```ts
/** Fetches events from relays according to the filter. */
function getFilter<K extends number>(filter: Filter<K>, opts: GetFilterOpts = {}): Promise<SignedEvent<K>[]> {
// TODO: actually fetch the events
return events;
}
// `events` is inferred as `SignedEvent<1>[]`
const events = await getFilter({ authors: [pubkey], kinds: [1] });
// `events` is inferred as `SignedEvent<1 | 6 | 7>[]`
const events = await getFilter({ authors: [pubkey], kinds: [1, 6, 7] });
```
> Make Filter a generic type accepting Kind

- README.md
Sender's pubkey was searched for in the `p` tag, where receiver's pubkey is found; use `event.pubkey` instead.
> Fix subtle inconsistency with NIP-04 in the decryption example

- nip19.ts
- nip21.ts
This is technically a breaking change since `BECH32_REGEX` is exported, but I doubt anyone is depending on it yet. I used it in a project and it bothered me that it was in nip21 when I wasn't doing stuff related to content parsing.
> Move BECH32_REGEX to nip19.ts

- package.json
Declarations were there, but not exported by "exports". This will make TSC and IDEs happy.
> Update package.json to export declarations

- relay.ts
- utils.test.ts
- utils.ts
The relay object uses incomingMessageQueue as a way to keep a fifo queue of messages incoming from open ws connections. This array is a fundamental part of the whole library and its .unshift() gets called a lot.
Because JavaScript Arrays are ArrayLists, their .unshift() method is work intensive (O(n)). When called every single remaining item in it needs to get a new index assigned, which makes them a suboptimal choice for queues.
I believe we should replace the standard ArrayList with data structure more suited for this task. I have added a MessageQueue class to the ulitities that implements a LinkedList, which exposes enqueue and dequeue methods(both O(1)).
Before I spent more time on this I wanted to get the maintainers input on this. Is there maybe something that I am missing that made …
> Replace array list queue with a linked list one 

- event.ts
The Kinds for ProfileBadge and BadgeDefiniton where swapped according to [NIP-58](https://github.com/nostr-protocol/nips/blob/master/58.md).
> Update Kind for ProfileBadge and BadgeDefinition

- nip27.test.ts
- nip27.ts
I received this event containing an invalid nip19: https://www.nostr.guru/e/bd107ef2033ff82a42e5a1377020771253d795568a6db0e2b53ad53cb35d73d7
It crashed my web server, which uses the `nip27.matchAll` function.
I wrote that function. I thought a try-catch wasn't needed since we do a regex match first, but this nip19 matches the regex and still crashes because it's invalid (I think). So now we add a try-catch.
I'm not sure if it should crash or not, or what this nip19 is trying to represent. But this is what caused it:
```
npub129tvj896hqqkljerxkccpj9flshwnw999v9uwn9lfmwlj8vnzwgq9y5llnpub1rujdpkd8mwezrvpqd2rx2zphfaztqrtsfg6w3vdnljdghs2q8qrqtt9u686
```
> Fix nip27.matchAll crash on invalid nip19

- nip19.ts
```ts
const npub = nip19.npubEncode('79c2cae114ea28a981e7559b4fe7854a473521a8d22a66bbab9fa248eb820ff6')
const decoded = nip19.decode(npub) // type is `{type: 'npub'; data: string}` !!
```
Takes advantage of [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) so that if the specific nip19 type is already known, decoding it will return the correct type without needing to check it.
I think it's a good idea for nip19 template literals to be a thing, because then you could guard functions like:
```ts
// only gets pubkey from npub and nsec
function getPubkey(value: `npub1${string}` | `nsec1${string}`): string {
return result.data // guaranteed to be a string
}
```
I'm using it for configuration in Ditto:
```ts
const Conf = {
get nsec() {
const …
```
> nip19: use template literal types

- pool.test.ts
- pool.ts
`_seenOn` map grows indefinitely, if you do not intend on using `seenOn`, you can disable it to save memory and improve performance.
> Add an option to disable `seenOn`

- event.ts
- index.ts
- nip98.test.ts
- nip98.ts
This PR adds 2 new functions related to [NIP 98](https://github.com/nostr-protocol/nips/blob/master/98.md)
`getToken` => Create, sign and returns the base64 token for Authorization header (with or without `Nostr` scheme)
Can be used client side with [NIP 07](https://github.com/nostr-protocol/nips/blob/master/07.md) (a project with a native custom element is coming soon)
`validateToken` => Validate the base64 encoded token passed in the Authorization header
Can be used server side to validate and authenticate the user
Question: Should `validateToken` returns the user public key (hex and/or npub) in an object instead of just true/false? It could be useful for backend developer to easily get the public key associated to the request.
> NIP-98: add getToken and validateToken

- package.json
solves problem of "scure/bip39 1.2.0 causing problem of "Can't resolve '@scure/bip39/wordlists/english' ... because it was resolved as fully specified "
Fixes #253
> Update package.json to upgrade scure/bip39

- README.md
- nip42.ts
- pool.ts
- relay.ts
this simplifies the code and makes the API more intuitive.
we used to need the event emitter thing because we were subscribing to the same relay to check if the event had been published, but that is not necessary now that we assume an OK response will always come.
closes https://github.com/nbd-wtf/nostr-tools/issues/262
> Turn `.publish()` into a normal async function returning a promise

- filter.ts
The current type has this problem:
```ts
const filter: Filter = {};
// Uncaught TypeError: Cannot read properties of undefined (reading 'map')
filter['#e'].map(console.log)
```
All the keys in `Filter` are already optional with `?`. To make tag queries optional we need `| undefined`
> Filter: let tag queries be undefined

- nip98.ts
This PR adds common HTTP methods: HEAD, PUT, CONNECT, OPTIONS, TRACE and PATCH.
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
> fix(nip98): Add support for common HTTP methods

- nip44.test.ts
- nip44.ts
https://github.com/nostr-protocol/nips/pull/715
Take two, this time using a custom TLV. Note: I've never used TLVs before, so a review to make sure it's correct and idiomatic would be appreciated.
> nip44 updates

- kinds.test.ts
- kinds.ts
Adds a low-ish level kinds module that deals directly with numbers, and may be used to classify events according to NIP-01.
I took some liberties with `isRegularKind`, which is not entirely specified in NIP-01. We should probably stop accepting NIPs that propose new kinds less than 1000 so we don't have to keep updating this function, unless it would provide core protocol functionality.
> Add kinds module to classify events by kind

- pool.ts
- relay.ts
This allows SimplePool users to specify a custom eoseSubTimeout for a single subscription instead of for the whole pool instance.
> Added eoseSubTimeout to pool's SubscriptionOptions

- event.test.ts
- event.ts
- pool.ts
Follow up to #288 
Now `verifySignature` will return `false` if the event id is invalid, which is probably the right behavior since it's the only function that checks it (ie `validateEvent` does not check it).
I also made `finishEvent` now return a `VerifiedEvent`, since in that case we also know it's definitely verified.
> verifySignature: return false if the id is invalid

- package.json
Another follow-up to #281, this adds TypeScript >= 5.0.0 as an optional peer dependency. Users of plain JavaScript should not get any errors or warnings, but if TypeScript less than 5 is installed, a warning will be shown.
> Make TypeScript >= 5.0.0 an optional peer dependency

- relay.test.ts
- relay.ts
Should allow an API like this:
```ts
const sub = relay.sub([{ kinds: [1] }])
for await (const event of sub.events) {
console.log(event) // I'm a kind 1 event!
}
```
It run forever until you break out of it (with a `break`). If you want to run it in the background you would typically put it inside a separate async function that isn't awaited:
```ts
async function processFilters(filters: Filter[]) {
const sub = relay.sub(filters)
for await (const event of sub.events) {
console.log(event) // I'm a kind 1 event!
}
}
processFilters() // now it runs in the background
console.log('hello') // this works
```
Creating async generators out of event emitters in JS is inherently dirty, but the API for users is much nicer. This has not been thoroughly tested and there might be problems with it.
> relay: `sub.events` async iterator

- nip13.ts
When I created the nip13 module, for some reason I glossed over the fact there was already a JavaScript implementation within the NIP-13 text itself: https://github.com/nostr-protocol/nips/blob/master/13.md#validating
I had pulled the implementation from Nostream, which is for Node.js, and adapted it to work in the browser. But apparently if you just do it the browser way it's much simpler.
> nip13: use a simpler implementation

- nip13.test.ts
- nip13.ts
Adds a function to mine the POW for an event. It's loosely adapted from Snort but I changed it quite a bit.
> nip13: add minePow function

- README.md
Remove assignment to `pubkey` from declaring an event because `pubkey` also assigned by `finishEvent`.
> Improve example for finishEvent

- pool.ts
just added mergeFilters to batchedList method
> edit batchedList and add mergeFilters to it

- build.js
- package.json
- tsconfig.json
Adds one entrypoint per file such that `import { generatePrivateKey } from 'nostr-tools/keys';` can be done from clients without having to import everything but the kitchen sink. For ESM and CJS, the IIFE version still bundles from `index.ts`
> Organize build, allow one entrypoint per file

- pool.test.ts
I'd like to advocate that for eliminating as many "ts-ignores" and "eslint-ignores" as possible to ensure the code base remains strongly typed throughout. This one is a bit of nitpick as it's in a test assertion, but my OCD couldn't let it slide. :)
I will follow up soon with another more meaningful one that isn't inside a test file.
> Clean up test with a minor refactor to delete the ts-ignore

- package.json
There was a bug in the package `@noble/curves` with version 1.1.0 when parsing strings with non-hex characters. It will not throw any error but keep processing with the wrong formatted string.
Here's the steps to re-produce:
```
const { getPublicKey } = require('nostr-tools')
const sk = "02336e32749f642c6a56ee709a01afe7ff8d2b268c04a7f;a0000308cd2382eb"
const pk = getPublicKey(sk)
```
The variable `sk` contains a non-hexadecimal character, I believe the function call `getPublicKey()` should throw an error here but it's keeping converting it to a public key.
> Update `@noble/curves` to 1.2.0

- nip11.test.ts
- nip11.ts
issue #85 was suggesting to create a nip11.ts file, with a requestRelayInfos function and types which represent the possible answers.
> nip11 - Types, requestRelayInfos() and tests

- relay.test.ts
- relay.ts
`relayConnect()` doesn't `await` on `relay.connect()` and just return `Relay`, so `await` on `relayConnect()` as the README won't work as expected (it should make sure that connection to a relay is established), I think.
I made `relayConnect` async function and correctly `await` on `relay.connect()`.
> Correctly wait until connection to a relay is established

- pool.ts
The current implementation of `ensureRelay` connects to relays **for the first time only**. The second invocation of `ensureRelay` doesn't try to reconnect the relay even if it is disconnected. 
This PR fixes that. It will try to connect if `relay` is disconnected.
The current implementation tries to send messages even if the connection is closed.
It causes the following error when I call `pool.subscribeMany([failedRelay], ...)`:
```
Uncaught (in promise) Error: sending on closed connection
```
https://github.com/nbd-wtf/nostr-tools/blob/a9acdada19e11ebb226e9decaae3533a51ca4010/pool.ts#L106
If this PR is merged, the connection error exception will be raised in this `try` block and it will be handled correctly.
https://github.com/nbd-wtf/nostr-tools/blob/a9acdada19e11ebb226e9decaae3533a51ca …
> ensureRelay reconnect

- index.ts
- package.json
I tried to import kinds from `nostr-tools/kinds` but it seems that it is not exported.
```
[vite] Internal server error: Missing "./kinds" specifier in "nostr-tools" package
```
This PR fixes that.
> export kinds

- build.js
When CommonJS modules of this package are imported from node scripts under the "CJS context", an error occurs:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /...snip.../node_modules/nostr-tools/lib/cjs/index.js from /...snip.../user_script.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
```
This is due to [this change](https://github.com/nbd-wtf/nostr-tools/commit/7f11c0c618449579bac0b38ca2bc4cef6cbd4b2b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R2), and I fixed it by applying [this hack](https://github.com/nbd-wtf/nostr-tools/blob/f727058a3a38ac4021f9e01d3772a320f4d3e4a3/build.js#L31-L36) to the CJS …
> fix problem when required from CommonJS

- helpers.ts
I noticed that the current implementation of yieldThread will consume memory.
The message channel will never be used after the call but there is still a `'message'` call-back function so GC cannot free it.
It is needed to call `removeEventHandler`.
If you run this script with `node` command like `node script.js`, the process will never finish.
```javascript
async function yieldThread() {
return new Promise(resolve => {
const ch = new MessageChannel()
ch.port1.addEventListener('message', resolve)
ch.port2.postMessage(0)
ch.port1.start()
})
}
yieldThread()
```
If there is removeEventListener, it will finish successfully.
```javascript
async function yieldThread() {
return new Promise(resolve => {
const ch = new MessageChannel()
const handler = () => {
ch.port1.removeEventListener('message', …
```
> fix yieldThread memory leak

- filter.test.ts
- filter.ts
When filtering events, it can sometimes be difficult to know when to stop. Obviously if the filter has a `limit` you can use it, but otherwise you may need to rely on timeouts or other cues.
But some filters have an intrinsic limit. For example, `{ ids: ["a", "b", "c" }` has an intrinsic limit is `3`.
If an intrinsic limit can be determined from the filter, `getFilterLimit` will return it. Otherwise it will return `Infinity`.
This is useful in multiple scenarios:
1. You can skip invalid filters entirely with `filters.filter((filter) => getFilterLimit(filter) > 0)`. This technique is usable on both clients and relays.
2. If you are querying events from a storage, you can cancel when the limit is reached, saving time.
3. You can use it to calculate the desired limit on your own filters …
> Add getFilterLimit function

- nip57.ts
Safeguards naive implementations from accidentally doing a GET on `https://localhost:8000/api/secret?hack=/.well-known/lnurlp/alex`, for example.
> NIP-57: build lnurl in more secure way

- package.json
- relay.test.ts
- added `mock-socket` as devDependency
- https://www.npmjs.com/package/mock-socket
- https://github.com/thoov/mock-socket
- ![image](https://github.com/nbd-wtf/nostr-tools/assets/25853688/0dcb9455-b609-4360-b3e4-4e9cda39b66e)
- refactored `relay.test.ts` with mock websocket.
> Implement Mock Websocket

- pure.ts
Some imports do not have the explicit extension and others do. In this case I fix core.ts which is giving error in some of my projects that use nostr-tools.
> Fix explicit file extension for core.ts

- nip05.ts
According to NIP-05 specification, the implementation must ignore HTTP redirect.
https://github.com/nostr-protocol/nips/blob/master/05.md#security-constraints
`fetch` API accepts the option as the second parameter.
`{ redirect: 'error' }` will cause an error if the endpoint returns 302 or something like that.
> ignore HTTP redirect in nip05

- jsr.json
Adds the required `jsr.json` file. Then it can be deployed with `deno publish` or `npx jsr publish`.
We should also fix #375
> Prepare for JSR publishing

- .github/workflows/publish.yml
This will automatically publish the package to JSR whenever you push a commit to master that changes the version number in `jsr.json`
> Publish to JSR with GitHub actions

- nip46.ts
NIP46 requires remote_user_pubkey as first param to connect. Context: https://github.com/nostrability/nostrability/issues/25#issuecomment-2018748964
> Fix pubkey param to nip46 connect

- core.test.ts
- core.ts
Adds a function to sort events, which is often needed when gathering events from untrusted sources such as relays.
Events are sorted reverse-chronologically by the `created_at` timestamp. If there is a tie with `created_at`, it sorts lexicographically by the event ID.
> Add stable sortEvents function

- nip46.ts
The hyphen (`-`) is missing in BUNKER_REGEX, this can invalidate some legit bunker urls when the `secret` contains this character.
https://datatracker.ietf.org/doc/html/rfc4648#section-5
> Add hyphen to BUNKER_REGEX

- abstract-relay.ts
The `count` method is wrapping the filters in an extra array. which makes it an invalid request according to [NIP-45](https://github.com/nostr-protocol/nips/blob/master/45.md#filters-and-return-values)
```json
["COUNT","count:1",[{"kinds":[1]}]]
```
```json
["COUNT","count:1",{"kinds":[1]}]
```
> Fix count request in anstract relay

- README.md
- index.ts
- jsr.json
- nip07.ts
- nip46.ts
- package.json
- relay.ts
This pull request includes:
- typescript interface for nip07;
- centralized nip46 and nip07 relay map into a named type and export it;
- include docs of how to include the nip07 type for browser environment;
I haven't finished testing it yet and it's not ready, but I opened the pull request to advance the code review
> including interface for nip07

- README.md
- nip06.test.ts
- nip06.ts
- relay.ts
Just fixing the lint and adding nip06 examples.
> Improving nip06 documentation

- filter.test.ts
- filter.ts
Filters with empty tag queries have an intrinsic limit of `0`.
> getFilterLimit: empty tags return 0

- nip94.test.ts
- nip94.ts
[NIP-94](https://github.com/nostr-protocol/nips/blob/master/94.md) defines `fallback` tag ([2c016b0](https://github.com/nostr-protocol/nips/commit/2c016b0659a8f29ad2420a4cd844a2dca4956407)). This PR add support for `fallback` tag.
I am not sure that this is really and widely used.
> support fallback tag of NIP-94

- nip11.ts
fix https://github.com/nbd-wtf/nostr-tools/issues/415
`max_subscriptions` was included, but missing a `s`.
Other params was included with they docs.
> fix typo and include missing attributes for nip11 and they docs

- abstract-pool.ts
I wanna extends AbstractSimplesPool to create and test other complementary implementations for my software, It will be so bad to change this to `protected`? Please 🙏
> Making AbstractSimplesPool more extensible

- abstract-pool.ts
I am suggesting the inclusion of two methods within the abstract pool.
`listConnectionStatus` to return a snapshot of all relays connection status in the pool.
`destroy` method, to close all connections in the pool (close method requires the relay list).
I have included then in my project abstract pool, but I wondered if you could consider these features as useful and interesting to be centralized in this library.
> methods for abstract pool

- nip96.ts
The NIP-96 uploadFile has a bug. This PR fixes it.
When using `fetch` API along with `FormData`, specifying `Content-Type` will cause error. It is because if we specify  `Content-Type: multipart/form-data`,  the browser will send it as is without considering "boundary".
> Warning: When using FormData to submit POST requests using XMLHttpRequest or the Fetch API with the multipart/form-data content type (e.g. when uploading files and blobs to the server), do not explicitly set the Content-Type header on the request. Doing so will prevent the browser from being able to set the Content-Type header with the boundary expression it will use to delimit form fields in the request body.
> https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects#sending_files_using_ …
> fix Content-Type bug in NIP-96 uploadFile

- filter.test.ts
- filter.ts
I was too lazy to do this before, but it matters for performance. I think this function is now "complete"
> getFilterLimit: handle parameterized replaceable events

- nip96.ts
this uploadFile function does not work with nostr.build because `Authorization` is not a [valid form field](https://github.com/nostr-protocol/nips/blob/master/96.md#upload.). nostr.build returns a 400 error.
> authorization should not be in the form data

- nip46.ts
This PR addresses a typo where the `nip44Decrypt` function call would send the `nip44_encrypt` request instead of the `nip44_decrypt` request.
This change provides a fix for the typo
> nip44Decrypt sends nip44_decrypt request

- abstract-pool.ts
- pool.test.ts
We need to query relays again to see where an event was published. This PR will solves that problem.
> make it possible to track relays on publish.

- nip06.test.ts
- nip06.ts
This PR adjusts the nip06 implementation so that it returns privatekeys as bytes to align with the rest of the lib
> nip06: return Uint8 instead of string

- nip17.test.ts
- nip17.ts
- nip28.ts
Added functions  wrapEvent, wrapManyEvents, unwrapEvent unwrapManyEvents and getWrappedEvents.
> Implemented NIP-17 support

- nip17.test.ts
- nip17.ts
- nip59.test.ts
- nip59.ts
Just some ajusts on nip17 and nip59
> Organizing and improving nip17 and nip59

- nip05.ts
Ran into issues with the nip05 profile fetching silently failing in the edge environment, here are the fixes with minor cleanup. Behavior is identical to the previouse one, and redirect will cause failure since non-200 code is returned.
- Fix "TypeError: Invalid redirect value, must be one of "follow" or "manual" ("error" won't be implemented since it does not make sense at the edge; use "manual" and check the response status code)." that is thrown when trying to use fetch in the edge environment  (e.g., workers)
- Cleanup types and variable definitions.
> Fix fetch to work in the edge and node environments, cleanup type issues

- abstract-relay.ts
- relay.test.ts
I don't know why, but there are relays (e.g wss://relay.nostr.bg) that does not send an `OK` message in response to an `EVENT` message. In that case we wait forever for it and the promise returned by `publish()` is never resolve/reject.
This PR adds a timeout and solves that problem.
> make publish() timeout.

- nip05.test.ts
Avoid test failures due to changes `/.well-known/nostr.json` in the real world.
> nip05: use stub to test queryProfile().

- nip19.test.ts
- nip19.ts
- nip21.test.ts
- nip27.test.ts
- nip27.ts
- references.ts
Related: https://github.com/nostr-protocol/nips/pull/1586
> nip19: remove note1.

- abstract-pool.ts
`id` was removed from `SubscriptionParams` in 804403f.
> remove unnecessary id from Omit keys.

- nip55.test.ts
- nip96.ts
The old version of the code was swallowing slightly more descriptive errors and re-throwing as json parse errors. It was also validating for a non-empty message, which was breaking nostrcheck.me uploads.
> Clean up nip96 upload validation and make it less strict

- nip57.ts
fixes #291 
I tried to keep it backwards compatible by allowing the event id and the event object.
> added support for zapping replaceable events

- nip18.test.ts
- nip18.ts
This pull request include backwards compatible implementation of NIP18 update for generic repost support for addressable events.
Includes throwing exceptions for invalid events and validating these exceptions in unit tests.
Please, validate if this implementation satisfies the needs for https://github.com/nbd-wtf/nostr-tools/issues/476.
> Generic repost event for addressable events

- README.md
- abstract-pool.ts
- abstract-relay.ts
- nip19.test.ts
- pool.ts
- Add `enablePing` option - nothing happens without it.
- Add fake `REQ` to ping relays in the browser.
- Set default ping and timeout to 45s.
See comments on #495 #498 for history.
> Get pingpong working in the browser with dummy REQ

- abstract-relay.ts
1. When `ws.onerror` or `ws.onclose` events are triggered before a successful connection (while `this._connected` is still `false`), the `this.onclose?.()` callback was not being called. This prevented the relay from being removed from the pool, making it impossible to reconnect via `ensureRelay`.
2. Potential error in close sequence: The `this.onclose?.()` callback was called after `this.ws?.close()`, which could potentially throw an error and prevent the `this.onclose?.()` callback from executing.
> relay: ensure onclose callback is triggered

- pool.test.ts
- relay.test.ts
- relay.ts
- test-helpers.ts
- Fix to allow `enablePing` to be passed to direct `Relay` instantiation.
- Flag to make `MockRelay` behave like an unresponsive relay.
- Added relay and pool tests for `enablePing`.
> Improvements to enablePing() & tests
