- pool.js
- relay.js
This implements EOSE without changing the api.
I don't like the code but it appears to work. Please check and suggest changes.
> EOSE nip-15

- nip06.js
- package.json
update packages described in #25
> replace micro-bip with @scure/bip, fix #25

- pool.js
- relay.js
allow access to the relay url that sent the EOSE
> Expose eose relay url

- index.d.ts
When using typscript is really annoying to create the whole Filter type, with this change it will be more comfortable use a filer. The next image shows  an example
> Filter type with optional atributtes

- index.d.ts
- pool.js
I spend a time studying the pool.js , at the same time i make some anotations.Maybe coud be a good option to add it.
> Documentation pool.js

- index.d.ts
- pool.js
- relay.js
More relay functions are exposed in TS . Also i add the possibility to get the relies on the pool and change the visibility. Before the solution could be remove and add the relay, however it would have a overhead cuz the connections them must done.
> Expose relay funcs

- index.d.ts
I missmatch the return value of the list, this might fix it
> fix return value getRelayList

- index.d.ts
I realized that tags were an array of array, if it is correct merge, if im wrong just discard
> Fix tag type

- index.d.ts
some event fields were missing
> event fields

- nip19.ts
> increase bech32.decode() and encode() string length parameter to 1500 

- README.md
> remove extra &&

- nip06.test.js
- nip06.ts
> nip06 passphrase

- relay.ts
* Add incoming messages to processing queue and process them on setInterval, so we don't block UI processing
* Optional `alreadyHaveEvent` param to `relayInit` so you can skip JSON.parse and event callback, if you already have the event in memory
* Catch errors in `ws.send(msg)`
* Resolve `untilOpen` on `ws.open`
> incoming message queue, alreadyHaveEvent check, msg.send catch

- README.md
Small fix of import SimplePool in new multiple relay docs.
> docs: import SimplePool fix

- event.ts
fixes #117
I saw failing tests in pool, but I don't think that was related as I see the same failures on master.
> Type unsigned events

- justfile
- package.json
- tsconfig.json
> add type definition

- filter.ts
https://github.com/nostr-protocol/nips/blob/master/50.md
> add search field to filter (NIP-50)

- pool.ts
- relay.ts
> Type sub event handler

- nip10.test.js
- nip10.ts
Also fixed pubkey relays being ignored.
Also fixed code style with prettier.
Sorry for the original #171 PR being a bit of a mess.
>  Fix explicit NIP-10 root/reply/mention markers parsed incorrectly 

- event.ts
Added the following badge kinds according to NIP 58
BadgeDefinition: 30008,
BadgeAward: 8,
ProfileBadge: 30009,
> added badge events

- event.ts
- index.ts
- keys.ts
- nip04.ts
- nip06.ts
- nip13.ts
- nip19.ts
- nip26.ts
- package.json
- yarn.lock
https://github.com/paulmillr/noble-curves
https://github.com/paulmillr/noble-curves#security
https://github.com/paulmillr/noble-curves#upgrading
> Switch from noble-secp256k1 to noble-curves

- relay.ts
Based on https://github.com/nostr-protocol/nips/pull/144/files
I am having a weird compilation error, which I can fix by removing the variable declarations that are causing problems, but @fiatjaf do you have any ideas?
```
✘ [ERROR] The symbol "id" has already been declared
relay.ts:162:18:
162 │               let id = data[1]
╵                   ~~
The symbol "id" was originally declared here:
relay.ts:149:18:
149 │               let id = data[1]
╵                   ~~
✘ [ERROR] The symbol "id" has already been declared
relay.ts:162:18:
162 │               let id = data[1]
╵                   ~~
The symbol "id" was originally declared here:
relay.ts:149:18:
149 │               let id = data[1]
╵                   ~~
✘ [ERROR] The symbol "id" has already been declared
relay.ts:162:18:
162 …
```
> Add support for `COUNT`

- index.ts
- nip42.test.js
- nip42.ts
- relay.ts
`relay.ts` had some type errors, it wasn't even building for me out of the box so I went and included a fix in this MR.
Fixes https://github.com/nbd-wtf/nostr-tools/issues/189
> feat: nip-42

- pool.ts
- relay.ts
Follow-up to #204 
It becomes possible to do this:
```ts
let relay = relayInit('wss://relay.damus.io/')
relay.sub([{ kinds: [1] }, { kinds: [2, 3] }]).on('event', (event) => {
event // `Event<1 | 2 | 3>` is inferred
})
relay.sub([{ authors: ['1234....'] }]).on('event', (event) => {
event // `Event<number>` is inferred
})
relay.sub([{ kinds: [] }]).on('event', (event) => {
event // `Event<never>` is inferred
})
```
> Infer relay event types from filter

- .eslintrc.json
- event.ts
- filter.ts
- nip04.ts
- nip25.ts
- nip26.ts
- nip42.ts
- nip57.ts
- utils.ts
Fixes typescript issues when trying to pass events of unknown kind into functions that shouldn't care. Functions that don't care about kind should accept an `Event<number>`.
More comments below.
> Improve event types

- nip05.test.js
- nip05.ts
Greatly simplify the nip05 lookup function with a good regex. Also parse the json response to make sure it's valid
> nip05 refactoring

- nip27.test.ts
There was a small issue with my test in #239.
The code itself is fine and it still has the desired behavior. I just had a typo in the test.
> Fix nip27 test

- nip05.test.ts
- nip27.ts
> Fix nip27 type

- filter.test.ts
- filter.ts
cf. https://github.com/nostr-protocol/nips/pull/666
> Keep up with the latest specs for since/until filter

- event.ts
- filter.ts
This is the smallest possible diff to fix https://github.com/nbd-wtf/nostr-tools/issues/275
It makes it easier for people to use nostr-tools for event kinds of any number.
> Event, Filter: allow any kind number

- index.ts
- nip44.test.ts
- nip44.ts
- package.json
- yarn.lock
https://github.com/nostr-protocol/nips/pull/715
> Add nip44 support

- event.ts
see https://github.com/nostr-protocol/nips/blob/master/94.md
> added new event kind 1063

- event.ts
This is an experiment with types:
```ts
import { verifiedSymbol, verifySignature, type Event } from 'nostr-tools'
const event: Event = { ... };
console.log(event[verifiedSymbol]) // `undefined` - the event has not been verified or rejected
verifySignature(event) // true
console.log(event[verifiedSymbol]) // `true` - the event has now been verified
verifySignature(event) // true, returns immediately instead of calling `schnorr.verify`
```
Now calling `verifySignature(event)` will set a `[Symbol(verified)]: true` on the event, so calling `verifySignature` multiple times on the same event will have no effect.
You can also guard functions to only allow verified events:
```ts
function validateAuthEvent(event: VerifiedEvent): event is VerifiedEvent<27235> {
// do stuff with the verified …
```
> Draft: Add a symbol to verified events

- event.ts
- index.ts
- nip47.test.ts
- nip47.ts
https://github.com/nostr-protocol/nips/blob/master/47.md
> add helper functions for nip-47 Nostr Wallet Connect

- nip98.test.ts
- nip98.ts
Updated `getToken` to include the request body payload hash in the event tags.
Updates 'validateEvent` to validate the payload hash is valid and matches the request body hash.
> NIP-98: Add support for payload tag

- nip27.ts
- nip30.test.ts
- nip30.ts
Provides similar functionality to nip27, searching and replacing custom emoji shortcodes.
> Add NIP-30 module for custom emojis

- nip40.test.ts
- nip40.ts
Adds helper functions for dealing with event expiration.
> Add NIP-40 module for event expiration

- nip98.test.ts
- nip98.ts
- added docs for all methods
- refactored with smaller and more readable functions
- added more test cases
- fixed possible bugs in checking tags:
`urlTag?.length !== 1 && urlTag?.[1] !== url`
that "length !== 1" doesn't make sense.
- fixed possible bugs in checking body:
`Boolean(body) && Object.keys(body).length > 0`
that would fail in non-object inputs.
> Nip98 enhancement

- nip99.test.ts
- nip99.ts
- implemented nip99 with detailed docs and proper types
- event validation
- event parser
- event generator
- added test cases for nip99
> Nip99 implementation

- .eslintrc.json
> suppress eqeqeq eslint rule

- filter.ts
- nip40.test.ts
- nip40.ts
there were some unformatted files caused some build warnings (and maybe errors I don't know).
- formatted.
> format with prettier

- nip11.test.ts
- nip42.test.ts
- pool.test.ts
- relay.test.ts
- test-helpers.ts
- refactored `newMockRelay` function to `MockRelay` class.
- enhanced mock relay implementation.
- added docs for MockRelay.
- updated `relay.test`, `pool.test`, `nip42.test` with new MockRelay class.
- ~~fixed a broken test in `nip11.test`~~
- reverted! it should be replaced with mock functions, as well. (actually there should be **NO** external network connections with third-party services at all, as they are subjected to change anytime and broke our tests.
> Enhance Mock Relay

- nip94.test.ts
- nip94.ts
- implemented nip94 helpers with docs
- added test cases
> Nip94 implementation

- nip96.test.ts
- nip96.ts
- patched an important un-covered error handling
- added proper test cases
> nip96: fix unexpected errors

- nip75.test.ts
- nip75.ts
- package.json
- implemented `NIP75: Zap Goals` with proper docs.
- added test cases with 100% coverage.
- added exports/nip75 to package.json
- bumped to v2.2.0
> Nip75 Implementation

- abstract-pool.ts
- abstract-relay.ts
- kinds.ts
- nip11.ts
- nip21.ts
- nip27.ts
- nip30.ts
- nip44.ts
- nip47.ts
- pure.ts
- relay.ts
- utils.ts
This addresses #375, fixing almost every file except nip44.ts. I will deal with that file in a separate MR.
> Fix (most) slow types by adding explicit return types

- README.md
- nip44.ts
Puts nip44 const into a static class so it doesn't have to infer types.
> NIP44: fix slow types

- .github/workflows/publish.yml
Let's see if this fixes it.
Sent from my iPhone
> publish: bun i

- tsconfig.json
Tell tsconfig to use ESM imports so it can resolve types correctly.
> tsconfig: moduleResolution Bundler

- abstract-relay.ts
- Fix for an occasional error thrown when the websocket is closed.
fixes #370
> fix: error thrown on ws close

- nip58.test.ts
- nip58.ts
- package.json
- added helpers for `nip58: Badges` with full doc
- Badge Definition
- Badge Award
- Profile Badges
- added test cases with %100 coverage
> Nip58 Implementation

- nip29.ts
- added more helpers based on updated NIP29 specifications.
- enhanced `subscribeRelayGroups` method.
- added docs.
> TODO: tests
**note:** This PR has some breaking changes for nip29 implementation.
> add and improve helpers for nip29

- package.json
Adding missing package.json exports for new nip59 module.
> export nip59

- nip19.test.ts
- nip19.ts
This is a follow-up work of 45b25c5.
> nip19: completely remove nrelay.

- abstract-relay.ts
https://github.com/nbd-wtf/nostr-tools/pull/452 added a `setTimeout` to deal with publish timeouts but that doesn't clear it when OK is received, this PR adds that for both publish and auth methods
> fix: clear timeout in publish and auth

- nip55.test.ts
- nip55.ts
Just an abstraction to build URI's.
> Added NIP-55

- abstract-relay.ts
- Receiving an `AUTH` message no longer clears `authPromise`
- The signing operation is now encapsulated within `authPromise`
> fix bug where concurrent auth calls returned only one response

- nip46.ts
Previously, resubscribe was triggered immediately on onclose, causing an infinite loop when offline. Now it only resubscribes when `sendRequest` is called.
> nip46: fix crash caused by endless resubscribe

- nip47.test.ts
- nip47.ts
> enhance parseConnectionString to support double slash URL format

- abstract-relay.ts
Implements a ping/pong heartbeat on platforms where the WebSocket implementation supports `.ping()`. Fixes #495.
TODO:
Here's a simple test script for trying it out (build nostr-tools first):
```javascript
#!/usr/bin/env node
import { fileURLToPath } from 'url';
import path from 'path';
import { SimplePool, useWebSocketImplementation } from '../nostr-tools/lib/esm/pool.js';
import WebSocket from 'ws';
useWebSocketImplementation(WebSocket);
export async function getRelayInfo(relayUrl) {
// Convert wss:// to https:// or ws:// to http://
const httpUrl = relayUrl.replace(/^ws/, 'http');
try {
const response = await fetch(httpUrl, {
headers: {
'Accept': 'application/nostr+json',
},
});
if (!response.ok) {
throw new Error(`HTTP error! status: ${response.status}`);
}
const data = await …
```
> Add a ping/pong mechanism to detect socket timeout on  #495
